### ISSUE TITLE
BMLauncher is incompatible with visual studio 2017 express

### ISSUE THREAD

**Issue by cobralyn** [emanuelpm/Blade-Mistress#1]
This error is quite useless, as it explains nothing.

After installing some stuff i was able to build everything else on a windows 10 box.

**Comment by emanuelpm** [comment]
What version of VS2017 Community do you have?  That is what I am using so it is odd you are having issues. I'll take a look this evening.

**Comment by emanuelpm** [comment]
Verified that it works on multiple Win 10 + VS2017 Community machines.  Are you sure you are using VS2017 Community?  Express was an older VS.

**Comment by emanuelpm** [comment]
Think I figured it out.  Make sure you install the Visual Studio component MFC and ATL support (I take it for granted).  The Visual Studio Installer is installed alongside VS2017 so you can easily re-run it and add components.  Let me know if you still have issues!

**Comment by cobralyn** [comment]
switching from express to community fixed it.
