### ISSUE TITLE
Server and client sections are not separated enough in source.

### ISSUE THREAD

**Issue by zaphod77** [emanuelpm/Blade-Mistress#10]
Specifically, the GPL requires providing the source to anyone who has the binary on request.  since people will need the client to play, they are entitled to request the source of the client.   Not distributing the source to the SERVER is fine, because the server binary is being kept to yourself. :) so not distributing the server source doesn't violate the GPL.

But because the client contains the server code, it's impossible to hand out the client source without also handing out the server source.

This needs to be fixed by making a separation of server and client files, removing the -s option from the client, and making a client project that doesn't contain the server only code files.  

This is easier said then done. :)

**Comment by zaphod77** [comment]
https://github.com/emanuelpm/Blade-Mistress/blob/942ae4957f890448810ef0fa6abdc583d67f17d4/Source/src/Puma/pumaMain.cpp#L280  what i'm talking about with the server inside the client.

**Comment by zaphod77** [comment]
I've been working on this, and on my personal copy in progress, i've made it so the client project includes no server code, and no flies included in the client project include any server headers, though i had to move a few constants into header files so they could be included in both client and server like the hotkeys and a few other enums.  Now i just nee dot work out a way to grab just the files needed for building a client separate form the server. this knocks about 600k off the filesize of he client exe.

**Comment by emanuelpm** [comment]
I agree, there should really be a split, but the purpose of this depot specifically is just to be an archive of the code as it was (with some bug fixes, thanks to those who submitted :).
