### ISSUE TITLE
Guild namechange build doesn't respect existing guild names.

### ISSUE THREAD

**Issue by zaphod77** [emanuelpm/Blade-Mistress#2]
https://github.com/emanuelpm/Blade-Mistress/blob/37d4697f32513df76ce1c495d68859bc95b434fd/Source/src/tower-map.cpp#L735

should be GUILDBILL_CHANGENAME instead of GUILDBILL_CHANGESTYLE

**Comment by emanuelpm** [comment]
Should be fixed in https://github.com/emanuelpm/Blade-Mistress/commit/64b2b93672c8f46d4a2ce03694f51553aeb5d65b
