### ISSUE TITLE
Tokens not saved and loaded properly

### ISSUE THREAD

**Issue by zaphod77** [emanuelpm/Blade-Mistress#3]
https://github.com/emanuelpm/Blade-Mistress/blob/942ae4957f890448810ef0fa6abdc583d67f17d4/Source/src/tokenManager.cpp#L199

https://github.com/emanuelpm/Blade-Mistress/blob/942ae4957f890448810ef0fa6abdc583d67f17d4/Source/src/tokenManager.cpp#L230

paths are different.  LOAD shoould be looking in serverdata directlry

**Comment by emanuelpm** [comment]
Should be fixed in https://github.com/emanuelpm/Blade-Mistress/commit/0acda21a1eeeba655280d4c8563ab21727dc827c
