### ISSUE TITLE
Wandering around at 250+N and E can wipe posses.

### ISSUE THREAD

**Issue by zaphod77** [emanuelpm/Blade-Mistress#4]
https://github.com/emanuelpm/Blade-Mistress/blob/2d75ee46286c6187213bc33c93ae270a9c121d42/Source/src/BBO-Savatar.cpp#L7546

as you can see, only you being in the normal realm is checked, and that you are close enough to the posse coordinates.

need to check to make sure the questpart's maptype is also equal to SPACE_GROUND. this will stop the lost monster issue.

&& (qt->mapType==SPACE_GROUND)

**Comment by emanuelpm** [comment]
Should be fixed in https://github.com/emanuelpm/Blade-Mistress/commit/369daae17b767692889b46066b582934378099c5
